
stages:
  - build
  - unit_test
  - profile
  - functional_test

##### Debug #####

debug_build_job:
  stage: build
  artifacts:
    paths:
      - build/bin/
      - build/test/
    expire_in: 3d
  script:
    - ./waf configure -d clean build
  only:
    - master

debug_unit_test_job:
  stage: unit_test
  script:
    - ./waf test
  dependencies:
    - debug_build_job
  only:
    - master

debug_valgrind_unit_test_job:
  stage: unit_test
  script:
    - ./waf test --valgrind
  dependencies:
    - debug_build_job
  only:
    - master

debug_profile_job:
  stage: profile
  script:
    - ./waf profile
  dependencies:
    - debug_build_job
  only:
    - master

debug_valgrind_profile_job:
  stage: profile
  script:
    - ./waf profile --valgrind
  dependencies:
    - debug_build_job
  only:
    - master

debug_hello_world_real_time_job:
  stage: functional_test
  script:
    - build/bin/IpcConsoleCleanup console
    - build/bin/HelloWorld &
    - export HELLO_PID=$!
    - sleep 5
    - kill -INT $HELLO_PID
    - cat profiles.json
  dependencies:
    - debug_build_job
  only:
    - master

debug_hello_world_historical_job:
  stage: functional_test
  script:
    #First check that historical runs are repeatable
    - build/bin/HelloWorld src/HelloWorld/HistoricalCI1.ini
    - build/bin/HelloWorld src/HelloWorld/HistoricalCI2.ini
    - cat profiles.json
    - diff historical1.log historical2.log
    #Then test against valgrind
    - rm -f historical2.log
    - valgrind build/bin/HelloWorld src/HelloWorld/HistoricalCI2.ini
    - cat profiles.json
    - diff historical1.log historical2.log
  dependencies:
    - debug_build_job
  only:
    - master

##### Release #####

release_build_job:
  stage: build
  artifacts:
    paths:
      - build/bin/
      - build/test/
    expire_in: 3d
  script:
    - ./waf configure clean build
  only:
    - master

release_unit_test_job:
  stage: unit_test
  script:
    - ./waf test
  dependencies:
    - release_build_job
  only:
    - master

release_valgrind_unit_test_job:
  stage: unit_test
  script:
    - ./waf test --valgrind
  dependencies:
    - release_build_job
  only:
    - master

release_profile_job:
  stage: profile
  script:
    - ./waf profile
  dependencies:
    - release_build_job
  only:
    - master

release_valgrind_profile_job:
  stage: profile
  script:
    - ./waf profile --valgrind
  dependencies:
    - release_build_job
  only:
    - master

release_hello_world_real_time_job:
  stage: functional_test
  script:
    - build/bin/IpcConsoleCleanup console
    - build/bin/HelloWorld &
    - export HELLO_PID=$!
    - sleep 5
    - kill -INT $HELLO_PID
    - cat profiles.json
  dependencies:
    - release_build_job
  only:
    - master

release_hello_world_historical_job:
  stage: functional_test
  script:
    #First check that historical runs are repeatable
    - build/bin/HelloWorld src/HelloWorld/HistoricalCI1.ini
    - build/bin/HelloWorld src/HelloWorld/HistoricalCI2.ini
    - cat profiles.json
    - diff historical1.log historical2.log
    #Then test against valgrind
    - rm -f historical2.log
    - valgrind build/bin/HelloWorld src/HelloWorld/HistoricalCI2.ini
    - cat profiles.json
    - diff historical1.log historical2.log
  dependencies:
    - release_build_job
  only:
    - master
