
stages:
  - build
  - unit_test
  - functional_test

build_job:
  stage: build
  artifacts:
    paths:
      - build/bin/
      - build/test/
    expire_in: 3d
  script:
    - ./waf configure clean build
  only:
    - master

unit_test_job:
  stage: unit_test
  script:
    - ./waf test
  dependencies:
    - build_job
  only:
    - master

profile_job:
  stage: functional_test
  script:
    - ./waf profile
  dependencies:
    - build_job
  only:
    - master
