
stages:
  - build
  - unit_test
  - functional_test

build_job:
  stage: build
  artifacts:
    paths:
      - build/bin/
      - build/test/
    expire_in: 3d
  script:
    - ./waf configure clean build
  only:
    - master

unit_test_job:
  stage: unit_test
  script:
    - ./waf test
  dependencies:
    - build_job
  only:
    - master

hello_world_job:
  stage: functional_test
  script:
    - build/bin/IpcConsoleCleanup console
    - build/bin/HelloWorld &
    - export HELLO_PID=$!
    - sleep 5
    - kill -INT $HELLO_PID
    - cat profiles.json
  dependencies:
    - build_job
  only:
    - master

profile_job:
  stage: functional_test
  script:
    - ./waf profile
  dependencies:
    - build_job
  only:
    - master
