
def build(bld):
	#Main library
	bld.stlib(
		source = bld.path.ant_glob('Werk/**/*.cpp', excl=[]),
		target = '../lib/Werk',
		name   = 'Werk',
	)

	#Unit tests
	bld.program(
		source = bld.path.ant_glob('WerkTest/**/*.cpp', excl=[]),
		target = '../test/WerkTest',
		use    = ['Werk'],
	)

	#Hello world
	bld.program(
		source = 'HelloWorld/Main.cpp',
		target = '../bin/HelloWorld',
		use    = ['Werk'],
	)
