
def build(bld):
	#Main library
	bld.stlib(
		source = bld.path.ant_glob('Werk/**/*.cpp', excl=[]),
		target = 'Werk',
		name   = 'Werk',
	)

	#Hello world
	bld.program(
		source = 'HelloWorld/Main.cpp',
		target = '../HelloWorld',
		use    = ['TemplateLibrary'],
	)
